package com.example.localization

import java.util.Locale

enum class AppLanguage(
    val code: String,
    val displayName: String,
    val nativeName: String,
    val locale: Locale
) {
    ENGLISH("en", "English", "English", Locale.US),
    SPANISH("es", "Spanish", "Español", Locale.forLanguageTag("es-ES")),
    HINDI("hi", "Hindi", "हिन्दी", Locale.forLanguageTag("hi-IN")),
    BENGALI("bn", "Bengali", "বাংলা", Locale.forLanguageTag("bn-IN"))
}

object AppStrings {
    fun get(key: String, language: AppLanguage): String {
        return translations[language]?.get(key) ?: translations[AppLanguage.ENGLISH]?.get(key) ?: key
    }

    private val translations = mapOf(
        AppLanguage.ENGLISH to mapOf(
            "app_title" to "CropShield AI",
            "app_tagline" to "AI Crop Health Companion",
            "tab_scanner" to "Diagnosis",
            "tab_weather" to "Weather & Risk",
            "tab_history" to "Field History",
            "tab_guide" to "Agronomy Guide",
            "take_photo" to "Take Photo",
            "select_gallery" to "Select Gallery",
            "try_sample" to "Try Sample Leaves:",
            "sample_tomato" to "Tomato Blight",
            "sample_corn" to "Healthy Corn",
            "diagnose_crop" to "Diagnose Crop Health",
            "analyzing_leaf" to "Analyzing leaf pathology...",
            "analyzing_sub" to "Scanning discoloration, necrotic spots, and fungal patterns...",
            "retake" to "Retake / Clear",
            "online" to "Online",
            "offline_banner" to "Offline Mode — Local Diagnostic Engine Active",
            "weather_warning_title" to "Fungal & Pest Risk Alert",
            "humidity" to "Humidity",
            "temperature" to "Temperature",
            "risk_high" to "High Risk: High humidity accelerates spore germination!",
            "read_aloud" to "Read Aloud",
            "stop_speech" to "Stop Audio",
            "symptoms" to "Identified Symptoms",
            "organic_remedies" to "Organic & Biological Remedies",
            "chemical_treatments" to "Chemical Treatments",
            "prevention_steps" to "Prevention Guidance",
            "confidence" to "Confidence",
            "severity" to "Severity",
            "healthy" to "Healthy",
            "diseased" to "Diseased",
            "save_to_history" to "Save to Field History",
            "saved_success" to "Diagnosis saved to history!",
            "search_history" to "Search crops, diseases...",
            "filter_all" to "All",
            "filter_healthy" to "Healthy",
            "filter_diseased" to "Diseased",
            "clear_all" to "Clear All",
            "no_history" to "No scan history yet. Capture or upload a leaf above!"
        ),
        AppLanguage.SPANISH to mapOf(
            "app_title" to "CropShield AI",
            "app_tagline" to "Compañero IA de Salud del Cultivo",
            "tab_scanner" to "Diagnóstico",
            "tab_weather" to "Clima y Riesgo",
            "tab_history" to "Historial",
            "tab_guide" to "Guía Agrícola",
            "take_photo" to "Tomar Foto",
            "select_gallery" to "Galería",
            "try_sample" to "Probar hojas de muestra:",
            "sample_tomato" to "Tizón de Tomate",
            "sample_corn" to "Maíz Sano",
            "diagnose_crop" to "Diagnosticar Cultivo",
            "analyzing_leaf" to "Analizando patología foliar...",
            "analyzing_sub" to "Escaneando decoloración, manchas necróticas y hongos...",
            "retake" to "Repetir / Borrar",
            "online" to "En línea",
            "offline_banner" to "Modo sin conexión — Motor local activo",
            "weather_warning_title" to "Alerta de Riesgo Fúngico y Plagas",
            "humidity" to "Humedad",
            "temperature" to "Temperatura",
            "risk_high" to "Riesgo Alto: ¡La alta humedad acelera las esporas!",
            "read_aloud" to "Escuchar Diagnóstico",
            "stop_speech" to "Detener Audio",
            "symptoms" to "Síntomas Identificados",
            "organic_remedies" to "Remedios Orgánicos y Biológicos",
            "chemical_treatments" to "Tratamientos Químicos",
            "prevention_steps" to "Guía de Prevención",
            "confidence" to "Confianza",
            "severity" to "Severidad",
            "healthy" to "Saludable",
            "diseased" to "Enfermo",
            "save_to_history" to "Guardar en Historial",
            "saved_success" to "¡Diagnóstico guardado en el historial!",
            "search_history" to "Buscar cultivos o plagas...",
            "filter_all" to "Todos",
            "filter_healthy" to "Sanos",
            "filter_diseased" to "Enfermos",
            "clear_all" to "Borrar Todo",
            "no_history" to "Sin historial aún. ¡Escanea una hoja para comenzar!"
        ),
        AppLanguage.HINDI to mapOf(
            "app_title" to "क्रॉपशील्ड एआई",
            "app_tagline" to "स्मार्ट फसल स्वास्थ्य साथी",
            "tab_scanner" to "निदान",
            "tab_weather" to "मौसम और जोखिम",
            "tab_history" to "खेत इतिहास",
            "tab_guide" to "कृषि मार्गदर्शिका",
            "take_photo" to "फोटो खींचें",
            "select_gallery" to "गैलरी से चुनें",
            "try_sample" to "नमूना पत्तियां जांचें:",
            "sample_tomato" to "टमाटर अगेती झुलसा",
            "sample_corn" to "स्वस्थ मक्का",
            "diagnose_crop" to "फसल का निदान करें",
            "analyzing_leaf" to "पत्ती की बीमारी का विश्लेषण जारी...",
            "analyzing_sub" to "धब्बे, फफूंद और लक्षणों की जांच की जा रही है...",
            "retake" to "पुनः प्रयास / साफ़ करें",
            "online" to "ऑनलाइन",
            "offline_banner" to "ऑफलाइन मोड — स्थानीय निदान इंजन सक्रिय",
            "weather_warning_title" to "फफूंद और कीट जोखिम चेतावनी",
            "humidity" to "नमी (आर्द्रता)",
            "temperature" to "तापमान",
            "risk_high" to "उच्च जोखिम: अधिक नमी से फंगल संक्रमण तेजी से फैलता है!",
            "read_aloud" to "आवाज में सुनें",
            "stop_speech" to "आवाज रोकें",
            "symptoms" to "पहचाने गए लक्षण",
            "organic_remedies" to "जैविक एवं प्राकृतिक उपचार (किफायती)",
            "chemical_treatments" to "रासायनिक उपचार",
            "prevention_steps" to "भविष्य की रोकथाम सलाह",
            "confidence" to "सटीकता",
            "severity" to "गंभीरता",
            "healthy" to "स्वस्थ",
            "diseased" to "रोगग्रस्त",
            "save_to_history" to "इतिहास में सहेजें",
            "saved_success" to "निदान सफलतापूर्वक सहेजा गया!",
            "search_history" to "फसल या रोग खोजें...",
            "filter_all" to "सभी",
            "filter_healthy" to "स्वस्थ",
            "filter_diseased" to "रोगग्रस्त",
            "clear_all" to "सभी हटाएं",
            "no_history" to "अभी कोई स्कैन इतिहास नहीं है। एक पत्ती की फोटो लें!"
        ),
        AppLanguage.BENGALI to mapOf(
            "app_title" to "ক্রপশিল্ড এআই",
            "app_tagline" to "এআই ফসল স্বাস্থ্য সহকারী",
            "tab_scanner" to "রোগ নির্ণয়",
            "tab_weather" to "আবহাওয়া ও ঝুঁকি",
            "tab_history" to "মাঠের ইতিহাস",
            "tab_guide" to "কৃষি সহায়িকা",
            "take_photo" to "ছবি তুলুন",
            "select_gallery" to "গ্যালারি থেকে নিন",
            "try_sample" to "নমুনা পাতা পরীক্ষা করুন:",
            "sample_tomato" to "টমেটোর ব্লাইট",
            "sample_corn" to "সুস্থ ভুট্টা",
            "diagnose_crop" to "ফসল পরীক্ষা করুন",
            "analyzing_leaf" to "পাতার রোগ বিশ্লেষণ করা হচ্ছে...",
            "analyzing_sub" to "পাতার দাগ ও ছত্রাক প্যাটার্ন স্ক্যান হচ্ছে...",
            "retake" to "পুনরায় চেষ্টা / মুছুন",
            "online" to "অনলাইন",
            "offline_banner" to "অফলাইন মোড — স্থানীয় ডায়াগনস্টিক সক্রিয়",
            "weather_warning_title" to "ছত্রাক ও পোকার আক্রমণ সতর্কতা",
            "humidity" to "বাতাসের আর্দ্রতা",
            "temperature" to "তাপমাত্রা",
            "risk_high" to "উচ্চ ঝুঁকি: অতিরিক্ত আর্দ্রতায় ছত্রাকের দ্রুত বিস্তার ঘটে!",
            "read_aloud" to "ভয়েসে শুনুন",
            "stop_speech" to "ভয়েস থামান",
            "symptoms" to "শনাক্তকৃত লক্ষণসমূহ",
            "organic_remedies" to "জৈব ও প্রাকৃতিক প্রতিকার (সাশ্রয়ী)",
            "chemical_treatments" to "রাসায়নিক চিকিৎসা",
            "prevention_steps" to "ভবিষ্যতের প্রতিরোধ ব্যবস্থা",
            "confidence" to "নির্ভুলতা",
            "severity" to "তীব্রতা",
            "healthy" to "সুস্থ",
            "diseased" to "আক্রান্ত",
            "save_to_history" to "ইতিহাসে সংরক্ষণ করুন",
            "saved_success" to "রোগের তথ্য সংরক্ষিত হয়েছে!",
            "search_history" to "ফসল বা রোগ খুঁজুন...",
            "filter_all" to "সবগুলো",
            "filter_healthy" to "সুস্থ",
            "filter_diseased" to "আক্রান্ত",
            "clear_all" to "সব মুছুন",
            "no_history" to "কোনো স্ক্যান ইতিহাস নেই। পাতার ছবি তুলুন বা আপলোড করুন!"
        )
    )
}
